### ISSUE TITLE
テーブル生成処理を見直し

### ISSUE THREAD

**Issue by Lycolia** [Lycolia/adiary-extends#24]
テーブルを`div class="article_table"`みたいなのでラップし、以下のCSSを当てることでテーブルスクロールを可能にする

```css
article_table {
  overflow: scroll;
}

article td {
  white-space: pre-line;
}
```
